"""
Base Rule Interface
===================
Abstract base class defining the contract all detection rules must follow.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Alert:
    """Represents a security alert generated by a detection rule."""

    timestamp: str
    severity: str
    alert_type: str
    rule_name: str
    description: str
    source_ip: Optional[str] = None
    username: Optional[str] = None
    severity_score: int = 0
    mitre_tactic: Optional[str] = None
    mitre_technique: Optional[str] = None
    incident_id: Optional[int] = None
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Serialize to a flat dictionary for JSON output."""
        return {
            "timestamp": self.timestamp,
            "severity": self.severity,
            "severity_score": self.severity_score,
            "alert_type": self.alert_type,
            "rule_name": self.rule_name,
            "description": self.description,
            "source_ip": self.source_ip,
            "username": self.username,
            "mitre_tactic": self.mitre_tactic,
            "mitre_technique": self.mitre_technique,
            "incident_id": self.incident_id,
            **self.metadata,
        }


class BaseRule(ABC):
    """Abstract base class for all detection rules."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique identifier for this rule."""
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description of what this rule detects."""
        ...

    @property
    def mitre_tactic(self) -> Optional[str]:
        """MITRE ATT&CK tactic (e.g., 'Credential Access')."""
        return None

    @property
    def mitre_technique(self) -> Optional[str]:
        """MITRE ATT&CK technique ID (e.g., 'T1110')."""
        return None

    @abstractmethod
    def evaluate(self, log_event: dict) -> Optional[Alert]:
        """Evaluate a log event. Return an Alert if triggered, else None."""
        ...

    @abstractmethod
    def reset_state(self) -> None:
        """Clear any internal state (counters, windows, etc.)."""
        ...
